### ISSUE TITLE
Question: How to use examples with a particular kit

### ISSUE THREAD

**Issue by 0Grit** [cypresssemiconductorco/Code-Examples-for-the-ModusToolbox-PSoC-6-SDK#2]
Trying to use these examples with the Prototyping Kit BT WiFi

Is there some manual configuration that needs to be done on my end or is there a setting that will select the target board?

**Comment by 0Grit** [comment]
@JimTrudeau

**Comment by JimTrudeau** [comment]
To a certain extent it varies based on the example. As I recall, that kit does use different pins for some common tasks, so some examples will not work "out of the box" for that kit. Look at the example document (a pdf) for the example, see if it mentions that kit. If it does not, tell me which example in particular you're looking at, and I'll see if I can help figure it out.

**Comment by 40Grit** [comment]
Any of the DMA and pwm examples.

**Comment by 40Grit** [comment]
Was hoping to find the" breathing led"  example for modus but looks like it is only for creator.

The smart io based led ramp example is a next best standin maybe.

**Comment by 40Grit** [comment]
See my cypress community post for further background.

https://community.cypress.com/thread/47154

**Comment by JimTrudeau** [comment]
Hey! Thanks for the link to the community thread. I replied to that and pointed at the DMA example for the WiFi-BT prototype kit. CE218552 in this repo. 

You see the list of examples in this repo. For some features, the kits are wired differently. For others, they are wired the same, so a design for one kit works for all kits.

DMA is wired differently on the Prototype kit. As well, that kit does not have an RGB LED. So if the example uses the RGB LED, it's not going to work as expected on the prototype kit. Similarly, the example I cited is designed for the WiFi-BT prototype kit. Because it uses DMA, it will not work on the other kits.

So, if the resources used are the same, then the example "just works." If they are not the same, you will need to do some work to port the example to a different kit. What work depends upon the resource that changes from kit to kit.

When what I call a "wiring" change is required, here's what you need to do. In the ModusToolbox IDE, create a new application. Pick the board you want to use. Create a starter project for that kit. Use the PioneerKitApp for a pioneer kit, and the ProtoKitApp for a prototype kit. Some of the basic setup is already in place in these starter apps (like LEDs and UARTs). 

Then open the design.modus file for the starter app, and replicate the design used in the example. But when you come to the different resource, make sure you use the pin assignments that are correct for the kit you are really using.

For what it's worth, I am not happy with that process for moving an example from one kit to another. We are working on making that a lot easier. 

HTH, and let me know if there are questions.

**Comment by 40Grit** [comment]
Thanks for the assistance!

"DMA is wired differently on the Prototype kit."

"Wired" I assume means configured differently based on the fact that the proto kit has PCB components on different pins?

**Comment by JimTrudeau** [comment]
Exactly.
